apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://3000-port-oikteer7hvwmfsb7.labs.kodekloud.com/gitops-admin/mlops-deploy.git"    
    targetRevision: HEAD
    path: "manifests"           
  destination:
    server: https://kubernetes.default.svc
    namespace: "default"    
